enable protogetter  liner
ydb-platform/ydb-go-sdk pull request #1043
Opened 2024-02-12 17:37 UTC by dlc-01

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #962 

## What is the new behavior?

-
-
-

## Other information

2024-02-19 10:56 UTC, neyguvj approved these changes

2024-02-19 10:58 UTC, neyguvj requested changes
Hello.
You need to resolve conflicts first.

2024-02-20 08:28 UTC, asmyasnikov commented on CHANGELOG.md
> +* Refactored internal packages by `protogetter` linter issues
No need to prepend line with internal changes. Users do not use this feature

2024-02-27 15:04 UTC, neyguvj approved these changes

2024-02-28 05:41 UTC, merged