added quoter implementations
ydb-platform/ydb-go-sdk pull request #1184
Opened 2024-04-05 21:06 UTC by asmyasnikov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #1183 

## What is the new behavior?

-
-
-

## Other information

2024-04-09 06:48 UTC, shmel1k requested changes

2024-04-09 06:48 UTC, shmel1k commented on internal/backoff/delay.go
> +func WithFastBackof(fast Backoff) delayOption {
WithFastBackoff!

2024-04-09 06:48 UTC, shmel1k commented on internal/backoff/delay.go
> +func WithSlowBackof(slow Backoff) delayOption {
WithSlowBackoff!

2024-04-23 07:01 UTC, rekby requested changes

2024-04-23 10:35 UTC, merged