refactoring retry package
ydb-platform/ydb-go-sdk pull request #199
Opened 2022-04-13 12:00 UTC by asmyasnikov

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Other information

2022-04-13 13:12 UTC, positiveviking requested changes

2022-04-13 13:12 UTC, positiveviking commented on retry/retry.go
> +func WithFastBackoff(slotDuration time.Duration, ceiling uint, jitterLimit float64) retryOption {
Нужны пояснения. Я бы вынес настройки в свяазнную структурку и написал там комментарии из `backoff.logBackoff`

2022-04-13 13:12 UTC, positiveviking commented on sugar/sugar.go
> +		}, retry.WithIdempotent(true))
Вот кажется что `With` тут реально лишний.
`retry.Idempotent` и `retry.NonIdempotent` тут читались бы отлично.

2022-04-15 13:16 UTC, asmyasnikov commented on sugar/sugar.go
> +		}, retry.WithIdempotent(true))
таки да, но это ломает единый стиль опций. Сейчас ВСЕ опции имеют префикс With.
ломать это правило стоит только при наличии другого понятного правила

2022-04-15 13:18 UTC, asmyasnikov commented on retry/retry.go
> +func WithIdempotent(idempotent bool) retryOption {
ack

2022-04-15 13:18 UTC, asmyasnikov commented on internal/backoff/backoff.go
> +	SlotDuration time.Duration
ack

2022-04-15 13:24 UTC, asmyasnikov commented on internal/backoff/type.go
> +	TypeNoBackoff Type = 1 << iota >> 1
Насчет избыточного хвоста Backoff - принято

2022-04-18 09:10 UTC, closed without merging